### PR TITLE
Task1

### PR DESCRIPTION
**Pull request by apgupta3303**
# Assign1/Task1*

## :recycle: Current situation & Problem
* Currently our app icon does not properly reflect the functionality of our app
* The accent color needs to be changed for visual appeal
* Our contacts page does not provide the contact information for Professor Aalami. *

## :gear: Release Notes 
* Added new app icon picture and profile picture to assets 
* Changed accent color in assets
* Changed contact information for Professor Aalami

## :books: Documentation
* I did not change any documentation

## :white_check_mark: Testing
* I did not perform any tests

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AdritRao** [comment]
Hi @apgupta3303, I just reviewed your PR and everything looks good! 👍

**Review by AdritRao — CHANGES_REQUESTED** [review]
Hi @apgupta3303, the code looks great 👍! 

Can you please update your branch to be on the latest version of main?

Thanks!
Adrit

**Comment by apgupta3303** [comment]
@AdritRao  Could you please review again?

**Review by AdritRao — APPROVED** [review]
Hi @apgupta3303, thank you for merging the main branch into your feature branch. Because another update was made to main, can you please ensure that your branch is up to date with the main branch again. After that, feel free to merge your branch! Thank you! 🚀

**Pull request merged**
